#!/usr/bin/env python3
"""Aggregate seeded bench runs into one table with 95 % confidence intervals and write docs/benchmarks.md.

    scripts/bench_report.py <name> [<name> ...] [--out docs/benchmarks.md] [--label name=text ...]

Per configuration (all runs <name>_<i> under ~/togsim_data/bench): cycles, attempts, success (Wilson 95 % CI),
picks/min = 60 / mean cycle time incl. waits (bootstrap over cycles), placement mean and p95 in mm (bootstrap over
placed products, ground truth), motion time per cycle, per-phase timeline means.
"""

import glob
import json
import math
import os
import random
import re
import sys

BENCH = os.path.expanduser("~/togsim_data/bench")
random.seed(1)


def wilson(k, n, z=1.96):
    if n == 0:
        return (0.0, 0.0, 0.0)
    p = k / n
    den = 1 + z * z / n
    c = (p + z * z / (2 * n)) / den
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / den
    return (p, max(0.0, c - h), min(1.0, c + h))


def boot(values, stat, n=2000):
    if not values:
        return (None, None, None)
    est = stat(values)
    reps = []
    for _ in range(n):
        sample = [random.choice(values) for _ in values]
        reps.append(stat(sample))
    reps.sort()
    return (est, reps[int(0.025 * (n - 1))], reps[int(0.975 * (n - 1))])


def p95(v):
    s = sorted(v)
    return s[min(len(s) - 1, int(math.ceil(0.95 * len(s)) - 1))]


def mean(v):
    return sum(v) / len(v)


def collect(name):
    cyc_times, placements, yaws, cycles, attempts, motion, tl = [], [], [], 0, 0, [], {}
    runs = sorted(glob.glob(f"{BENCH}/{name}_[0-9]*.json"))
    for js in runs:
        run = js[:-5]
        log = open(os.path.join(run, "run_cycle.log")).read() if os.path.isdir(run) else ""
        d = json.load(open(js))
        cycles += d.get("cycles", 0)
        attempts += d.get("attempts", 0)
        if d.get("motion_mean_s"):
            motion.append(d["motion_mean_s"])
        for k, v in (d.get("timeline") or {}).items():
            tl.setdefault(k, []).append(v)
        # throughput = intervals between consecutive cycle completions (wall-clock stamps), i.e. including the waits
        stamps = [float(x) for x in re.findall(r"\[([0-9.]+)\] \[run_cycle\]: cycle \d+: ", log)]
        cyc_times += [b - a for a, b in zip(stamps, stamps[1:], strict=False) if 0.0 < b - a < 60.0]
        for m in re.finditer(r"placed v\d+ -> \S+ \(\S+ in \S+\): ([0-9.]+) mm off centre, yaw ([-+0-9.]+) deg", log):
            placements.append(float(m.group(1)))
            yaws.append(abs(float(m.group(2))))
    return {
        "runs": len(runs),
        "cycles": cycles,
        "attempts": attempts,
        "cycle_times": cyc_times,
        "placements": placements,
        "yaws": yaws,
        "motion": motion,
        "timeline": {k: mean(v) for k, v in tl.items()},
    }


def fmt_ci(t, digits=1, unit=""):
    if t[0] is None:
        return "–"
    return f"{t[0]:.{digits}f} [{t[1]:.{digits}f}–{t[2]:.{digits}f}]{unit}"


def main():
    args = sys.argv[1:]
    out = "docs/benchmarks.md"
    labels = {}
    names = []
    i = 0
    while i < len(args):
        if args[i] == "--out":
            out = args[i + 1]
            i += 2
        elif args[i] == "--label":
            k, _, v = args[i + 1].partition("=")
            labels[k] = v
            i += 2
        else:
            names.append(args[i])
            i += 1
    rows = []
    for name in names:
        c = collect(name)
        if not c["runs"]:
            print(f"no runs for {name}", file=sys.stderr)
            continue
        succ = wilson(c["cycles"], c["attempts"])
        cpm = boot(c["cycle_times"], lambda v: 60.0 / mean(v)) if c["cycle_times"] else (None, None, None)
        pm = boot(c["placements"], mean)
        pp = boot(c["placements"], p95)
        yaw = boot(c["yaws"], mean)
        tl = c["timeline"]
        rows.append(
            f"| {labels.get(name, name)} | {c['runs']}×{c['cycles'] // max(1, c['runs'])} | "
            f"{c['cycles']}/{c['attempts']} = {100 * succ[0]:.0f} % [{100 * succ[1]:.0f}–{100 * succ[2]:.0f}] | "
            f"{fmt_ci(cpm)} | {fmt_ci(pm)} | {fmt_ci(pp)} | {fmt_ci(yaw)} | "
            f"{mean(c['motion']):.2f} | idle {tl.get('idle', 0):.2f} / approach {tl.get('approach', 0):.2f} / "
            f"transfer {tl.get('transfer', 0):.2f} |"
        )
    table = (
        "| configuration | runs×cycles | success (95 % CI) | picks/min (95 % CI) | placement mean mm | "
        "placement p95 mm | yaw mean ° | motion s | phases s |\n|---|---|---|---|---|---|---|---|---|\n"
        + "\n".join(rows)
        + "\n"
    )
    print(table)
    if out:
        head = (
            "# Benchmarks\n\nGenerated by `scripts/bench_report.py` from seeded runs of `scripts/bench.sh` "
            "(vision perception, ground truth only for the metrics). Confidence intervals: Wilson for success, "
            "bootstrap over cycles (picks/min) and over placed products (placement).\n\n"
        )
        os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
        with open(out, "w") as f:
            f.write(head + table)


if __name__ == "__main__":
    main()
